import { UserRole } from '@/generated/prisma';
import { Permission, type PermissionKey } from './permissions';

export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  SUPER_ADMIN: Object.values(Permission),

  TENANT_ADMIN: [
    Permission.TENANT_READ,
    Permission.TENANT_UPDATE,
    Permission.USER_READ,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_MANAGE_ROLES,
    Permission.CONVERSATION_READ,
    Permission.CONVERSATION_CREATE,
    Permission.CONVERSATION_ASSIGN,
    Permission.CONVERSATION_CLOSE,
    Permission.TICKET_READ,
    Permission.TICKET_CREATE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_ASSIGN,
    Permission.TICKET_DELETE,
    Permission.KB_READ,
    Permission.KB_CREATE,
    Permission.KB_UPDATE,
    Permission.KB_DELETE,
    Permission.KB_PUBLISH,
    Permission.AI_CONFIG_READ,
    Permission.AI_CONFIG_MANAGE,
    Permission.INTEGRATION_READ,
    Permission.INTEGRATION_MANAGE,
    Permission.ANALYTICS_READ,
    Permission.AUDIT_LOG_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_UPDATE,
  ],

  SUPERVISOR: [
    Permission.TENANT_READ,
    Permission.USER_READ,
    Permission.CONVERSATION_READ,
    Permission.CONVERSATION_ASSIGN,
    Permission.CONVERSATION_CLOSE,
    Permission.TICKET_READ,
    Permission.TICKET_UPDATE,
    Permission.TICKET_ASSIGN,
    Permission.KB_READ,
    Permission.KB_CREATE,
    Permission.KB_UPDATE,
    Permission.KB_PUBLISH,
    Permission.AI_CONFIG_READ,
    Permission.ANALYTICS_READ,
    Permission.AUDIT_LOG_READ,
    Permission.SETTINGS_READ,
  ],

  AGENT: [
    Permission.CONVERSATION_READ,
    Permission.CONVERSATION_CREATE,
    Permission.CONVERSATION_CLOSE,
    Permission.TICKET_READ,
    Permission.TICKET_UPDATE,
    Permission.KB_READ,
    Permission.SETTINGS_READ,
  ],

  CUSTOMER: [
    Permission.CONVERSATION_READ_OWN,
    Permission.CONVERSATION_CREATE,
    Permission.TICKET_READ_OWN,
    Permission.TICKET_CREATE,
    Permission.KB_READ,
  ],
};
